<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Daftar Admin | EcoCraft</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root{--canvas:#fbf9f5;--ink:#1b2520;--muted:#717e77;--brand:#1e4b38;--accent:#6b5844;--line:#e5dfd5}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--canvas);color:var(--ink);font-family:'Plus Jakarta Sans',sans-serif;display:grid;place-items:center;padding:24px}a{color:inherit;text-decoration:none}.card{width:min(650px,100%);padding:clamp(28px,5vw,56px);background:#fff;border:1px solid var(--line);border-radius:20px;box-shadow:0 20px 48px -8px rgba(27,37,32,.14)}.brand{display:flex;align-items:center;gap:10px;color:var(--brand);font-weight:800;margin-bottom:42px}.brand img{width:34px;height:34px}.eyebrow{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.card h1{font:600 46px/1.05 'EB Garamond',serif;margin:10px 0}.lead{color:var(--muted);font-size:13px;line-height:1.7;margin:0 0 26px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:7px}.field input{width:100%;min-height:44px;padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:#f8f6f2;font:inherit}.full{grid-column:1/-1}.btn{width:100%;min-height:46px;border:0;border-radius:8px;background:var(--brand);color:#fff;font:700 13px 'Plus Jakarta Sans';cursor:pointer}.alert{padding:11px 13px;border-radius:8px;background:#ffebe6;color:#8b351f;font-size:12px;margin-bottom:18px}.alert ul{margin:0;padding-left:18px}.footer{text-align:center;color:var(--muted);font-size:12px;margin-top:22px}.footer a{color:var(--brand);font-weight:800}@media(max-width:600px){body{padding:12px}.card{padding:28px 22px}.card h1{font-size:38px}.grid{grid-template-columns:1fr}.full{grid-column:auto}}
    </style>
</head>
<body><main class="card"><a class="brand" href="{{ route('customer.dashboard') }}"><img src="{{ asset('assets/logo/logo.png') }}" alt="EcoCraft"><span>EcoCraft · Admin</span></a><div class="eyebrow">Registrasi internal</div><h1>Buat akun admin.</h1><p class="lead">Gunakan akses ini untuk mengelola kurasi dan operasional EcoCraft.</p>@if($errors->any())<div class="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<form method="POST" action="{{ route('admin.register.submit') }}">@csrf<div class="grid"><div class="field"><label for="name">Nama lengkap</label><input id="name" name="name" value="{{ old('name') }}" required></div><div class="field"><label for="phone_number">Nomor telepon</label><input id="phone_number" name="phone_number" value="{{ old('phone_number') }}" required></div><div class="field full"><label for="email">Email admin</label><input id="email" type="email" name="email" value="{{ old('email') }}" required></div><div class="field"><label for="password">Kata sandi</label><input id="password" type="password" name="password" required></div><div class="field"><label for="password_confirmation">Konfirmasi kata sandi</label><input id="password_confirmation" type="password" name="password_confirmation" required></div><div class="full"><button class="btn" type="submit">Buat akun admin</button></div></div></form><div class="footer">Sudah punya akses? <a href="{{ route('admin.login') }}">Masuk sebagai admin</a></div></main></body>
</html>
