<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }} | EcoCraft</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root{--canvas:#fbf9f5;--ink:#1b2520;--muted:#717e77;--brand:#1e4b38;--accent:{{ $role === 'admin' ? '#6b5844' : '#c86d51' }};--line:#e5dfd5;--panel:{{ $role === 'admin' ? '#ece9e2' : '#e7f2e9' }};}
        *{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--canvas);color:var(--ink);font-family:'Plus Jakarta Sans',sans-serif;display:grid;place-items:center;padding:24px}a{color:inherit;text-decoration:none}
        .shell{width:min(1040px,100%);display:grid;grid-template-columns:1.05fr .95fr;border:1px solid var(--line);border-radius:20px;overflow:hidden;background:#fff;box-shadow:0 20px 48px -8px rgba(27,37,32,.14)}.panel{padding:clamp(28px,5vw,58px)}.brand{display:flex;align-items:center;gap:10px;color:var(--brand);font-weight:800;margin-bottom:56px}.brand img{width:34px;height:34px;object-fit:contain}.eyebrow{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.panel h1{font:600 clamp(34px,4vw,50px)/1.05 'EB Garamond',serif;margin:10px 0}.lead{color:var(--muted);font-size:14px;line-height:1.7;margin:0 0 28px}.field{margin-bottom:17px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:7px}.field input{width:100%;min-height:46px;padding:11px 13px;border:1px solid var(--line);border-radius:8px;background:#f8f6f2;font:inherit}.btn{display:flex;justify-content:center;align-items:center;width:100%;min-height:46px;border:1px solid var(--brand);border-radius:8px;background:var(--brand);color:#fff;font:700 13px 'Plus Jakarta Sans';cursor:pointer}.alert{padding:11px 13px;border-radius:8px;background:#ffebe6;color:#8b351f;font-size:12px;margin-bottom:18px}.alert ul{margin:0;padding-left:18px}.footer{text-align:center;color:var(--muted);font-size:12px;margin-top:22px}.footer a{color:var(--brand);font-weight:800}.art{min-height:560px;padding:36px;display:flex;align-items:flex-end;background:linear-gradient(180deg,rgba(30,75,56,.05),rgba(30,75,56,.86)),url('{{ asset('assets/images/collection/banner welcome.png') }}') center/cover}.art h2{color:#fff;font:600 44px/1 'EB Garamond',serif;margin:0 0 8px}.art p{color:rgba(255,255,255,.82);font-size:13px;line-height:1.6;max-width:300px;margin:0}@media(max-width:760px){body{padding:12px}.shell{grid-template-columns:1fr}.art{min-height:190px;order:-1;padding:24px}.art h2{font-size:32px}.panel{padding:28px 22px}.brand{margin-bottom:30px}}
    </style>
</head>
<body><main class="shell"><section class="panel"><a class="brand" href="{{ route('customer.dashboard') }}"><img src="{{ asset('assets/logo/logo.png') }}" alt="EcoCraft"><span>EcoCraft · {{ $role === 'admin' ? 'Admin' : 'Seller' }}</span></a><div class="eyebrow">{{ $title }}</div><h1>{{ $heading }}</h1><p class="lead">{{ $lead }}</p>@if(session('success'))<div class="alert" style="background:#e5f3e9;color:#1e4b38">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<form method="POST" action="{{ $action }}">@csrf<div class="field"><label for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email') }}" required autofocus></div><div class="field"><label for="password">Kata sandi</label><input id="password" type="password" name="password" required></div><button class="btn" type="submit">Masuk sebagai {{ $role === 'admin' ? 'Admin' : 'Seller' }}</button></form>@if(!empty($registerUrl))<div class="footer">Belum punya akun? <a href="{{ $registerUrl }}">Daftar {{ $role === 'admin' ? 'admin' : 'seller' }}</a></div>@endif</section><aside class="art"><div><h2>{{ $role === 'admin' ? 'Kurasi dengan teliti.' : 'Jual dengan makna.' }}</h2><p>{{ $role === 'admin' ? 'Pastikan setiap karya yang hadir di EcoCraft tetap terpercaya dan berdampak.' : 'Bawa karya lokal dan material berkelanjutanmu ke komunitas EcoCraft.' }}</p></div></aside></main></body>
</html>
